package edu.tongji.anliantest.model;

// Generated 2014-9-30 13:52:24 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ConsumerResourceItem generated by hbm2java
 */
public class ConsumerResourceItem implements java.io.Serializable {

	private Integer itemId;
	private ConsumerResourceTable consumerResourceTable;
	private EmployeeInfo employeeInfoByResourceReceiverId;
	private EmployeeInfo employeeInfoByResourceReturnerId;
	private String resourceName;
	private Date submitTime;
	private Date returnTime;
	private Integer resourceQuantity;

	public ConsumerResourceItem() {
	}

	public ConsumerResourceItem(ConsumerResourceTable consumerResourceTable,
			EmployeeInfo employeeInfoByResourceReceiverId,
			EmployeeInfo employeeInfoByResourceReturnerId, String resourceName,
			Date submitTime, Date returnTime, Integer resourceQuantity) {
		this.consumerResourceTable = consumerResourceTable;
		this.employeeInfoByResourceReceiverId = employeeInfoByResourceReceiverId;
		this.employeeInfoByResourceReturnerId = employeeInfoByResourceReturnerId;
		this.resourceName = resourceName;
		this.submitTime = submitTime;
		this.returnTime = returnTime;
		this.resourceQuantity = resourceQuantity;
	}

	public Integer getItemId() {
		return this.itemId;
	}

	public void setItemId(Integer itemId) {
		this.itemId = itemId;
	}

	public ConsumerResourceTable getConsumerResourceTable() {
		return this.consumerResourceTable;
	}

	public void setConsumerResourceTable(
			ConsumerResourceTable consumerResourceTable) {
		this.consumerResourceTable = consumerResourceTable;
	}

	public EmployeeInfo getEmployeeInfoByResourceReceiverId() {
		return this.employeeInfoByResourceReceiverId;
	}

	public void setEmployeeInfoByResourceReceiverId(
			EmployeeInfo employeeInfoByResourceReceiverId) {
		this.employeeInfoByResourceReceiverId = employeeInfoByResourceReceiverId;
	}

	public EmployeeInfo getEmployeeInfoByResourceReturnerId() {
		return this.employeeInfoByResourceReturnerId;
	}

	public void setEmployeeInfoByResourceReturnerId(
			EmployeeInfo employeeInfoByResourceReturnerId) {
		this.employeeInfoByResourceReturnerId = employeeInfoByResourceReturnerId;
	}

	public String getResourceName() {
		return this.resourceName;
	}

	public void setResourceName(String resourceName) {
		this.resourceName = resourceName;
	}

	public Date getSubmitTime() {
		return this.submitTime;
	}

	public void setSubmitTime(Date submitTime) {
		this.submitTime = submitTime;
	}

	public Date getReturnTime() {
		return this.returnTime;
	}

	public void setReturnTime(Date returnTime) {
		this.returnTime = returnTime;
	}

	public Integer getResourceQuantity() {
		return this.resourceQuantity;
	}

	public void setResourceQuantity(Integer resourceQuantity) {
		this.resourceQuantity = resourceQuantity;
	}

}
