package edu.tongji.anliantest.model;

// Generated 2014-5-8 16:08:44 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ConsumerResourceTable generated by hbm2java
 */
@Entity
@Table(name = "consumer_resource_table", catalog = "anliantest")
public class ConsumerResourceTable implements java.io.Serializable {

	private Integer tableId;
	private ProjectInfo projectInfo;
	private String tableNum;
	private String tableType;
	private Set<ConsumerResourceItem> consumerResourceItems = new HashSet<ConsumerResourceItem>(
			0);

	public ConsumerResourceTable() {
	}

	public ConsumerResourceTable(ProjectInfo projectInfo, String tableNum,
			String tableType, Set<ConsumerResourceItem> consumerResourceItems) {
		this.projectInfo = projectInfo;
		this.tableNum = tableNum;
		this.tableType = tableType;
		this.consumerResourceItems = consumerResourceItems;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "table_id", unique = true, nullable = false)
	public Integer getTableId() {
		return this.tableId;
	}

	public void setTableId(Integer tableId) {
		this.tableId = tableId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id")
	public ProjectInfo getProjectInfo() {
		return this.projectInfo;
	}

	public void setProjectInfo(ProjectInfo projectInfo) {
		this.projectInfo = projectInfo;
	}

	@Column(name = "table_num", length = 13)
	public String getTableNum() {
		return this.tableNum;
	}

	public void setTableNum(String tableNum) {
		this.tableNum = tableNum;
	}

	@Column(name = "table_type", length = 3)
	public String getTableType() {
		return this.tableType;
	}

	public void setTableType(String tableType) {
		this.tableType = tableType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "consumerResourceTable")
	public Set<ConsumerResourceItem> getConsumerResourceItems() {
		return this.consumerResourceItems;
	}

	public void setConsumerResourceItems(
			Set<ConsumerResourceItem> consumerResourceItems) {
		this.consumerResourceItems = consumerResourceItems;
	}

}
