package edu.tongji.anliantest.model;

// Generated 2014-9-30 13:52:24 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ContractReviewRecordTable generated by hbm2java
 */
public class ContractReviewRecordTable implements java.io.Serializable {

	private Integer tableId;
	private EmployeeInfo employeeInfo;
	private ProjectInfo projectInfo;
	private String tableNum;
	private String tableStatus;
	private Date tableTime;
	private Set contractReviewRecordItems = new HashSet(0);

	public ContractReviewRecordTable() {
	}

	public ContractReviewRecordTable(EmployeeInfo employeeInfo,
			ProjectInfo projectInfo, String tableNum, String tableStatus,
			Date tableTime, Set contractReviewRecordItems) {
		this.employeeInfo = employeeInfo;
		this.projectInfo = projectInfo;
		this.tableNum = tableNum;
		this.tableStatus = tableStatus;
		this.tableTime = tableTime;
		this.contractReviewRecordItems = contractReviewRecordItems;
	}

	public Integer getTableId() {
		return this.tableId;
	}

	public void setTableId(Integer tableId) {
		this.tableId = tableId;
	}

	public EmployeeInfo getEmployeeInfo() {
		return this.employeeInfo;
	}

	public void setEmployeeInfo(EmployeeInfo employeeInfo) {
		this.employeeInfo = employeeInfo;
	}

	public ProjectInfo getProjectInfo() {
		return this.projectInfo;
	}

	public void setProjectInfo(ProjectInfo projectInfo) {
		this.projectInfo = projectInfo;
	}

	public String getTableNum() {
		return this.tableNum;
	}

	public void setTableNum(String tableNum) {
		this.tableNum = tableNum;
	}

	public String getTableStatus() {
		return this.tableStatus;
	}

	public void setTableStatus(String tableStatus) {
		this.tableStatus = tableStatus;
	}

	public Date getTableTime() {
		return this.tableTime;
	}

	public void setTableTime(Date tableTime) {
		this.tableTime = tableTime;
	}

	public Set getContractReviewRecordItems() {
		return this.contractReviewRecordItems;
	}

	public void setContractReviewRecordItems(Set contractReviewRecordItems) {
		this.contractReviewRecordItems = contractReviewRecordItems;
	}

}
