package edu.tongji.anliantest.model;

// Generated 2014-9-30 13:52:24 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ContractReviewRecordItem generated by hbm2java
 */
public class ContractReviewRecordItem implements java.io.Serializable {

	private Integer itemId;
	private DepartmentInfo departmentInfo;
	private ContractReviewRecordTable contractReviewRecordTable;
	private String reviewContent;
	private String reviewComment;
	private String itemStatus;
	private Date itemTime;

	public ContractReviewRecordItem() {
	}

	public ContractReviewRecordItem(DepartmentInfo departmentInfo,
			ContractReviewRecordTable contractReviewRecordTable,
			String reviewContent, String reviewComment, String itemStatus,
			Date itemTime) {
		this.departmentInfo = departmentInfo;
		this.contractReviewRecordTable = contractReviewRecordTable;
		this.reviewContent = reviewContent;
		this.reviewComment = reviewComment;
		this.itemStatus = itemStatus;
		this.itemTime = itemTime;
	}

	public Integer getItemId() {
		return this.itemId;
	}

	public void setItemId(Integer itemId) {
		this.itemId = itemId;
	}

	public DepartmentInfo getDepartmentInfo() {
		return this.departmentInfo;
	}

	public void setDepartmentInfo(DepartmentInfo departmentInfo) {
		this.departmentInfo = departmentInfo;
	}

	public ContractReviewRecordTable getContractReviewRecordTable() {
		return this.contractReviewRecordTable;
	}

	public void setContractReviewRecordTable(
			ContractReviewRecordTable contractReviewRecordTable) {
		this.contractReviewRecordTable = contractReviewRecordTable;
	}

	public String getReviewContent() {
		return this.reviewContent;
	}

	public void setReviewContent(String reviewContent) {
		this.reviewContent = reviewContent;
	}

	public String getReviewComment() {
		return this.reviewComment;
	}

	public void setReviewComment(String reviewComment) {
		this.reviewComment = reviewComment;
	}

	public String getItemStatus() {
		return this.itemStatus;
	}

	public void setItemStatus(String itemStatus) {
		this.itemStatus = itemStatus;
	}

	public Date getItemTime() {
		return this.itemTime;
	}

	public void setItemTime(Date itemTime) {
		this.itemTime = itemTime;
	}

}
