package edu.tongji.anliantest.model;

// Generated 2014-9-30 13:52:24 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * DepartmentInfo generated by hbm2java
 */
public class DepartmentInfo implements java.io.Serializable {

	private Integer departmentId;
	private String departmentName;
	private String departmentDesc;
	private Set contractReviewRecordItems = new HashSet(0);
	private Set workTaskItems = new HashSet(0);
	private Set employeeInfos = new HashSet(0);

	public DepartmentInfo() {
	}

	public DepartmentInfo(String departmentName) {
		this.departmentName = departmentName;
	}

	public DepartmentInfo(String departmentName, String departmentDesc,
			Set contractReviewRecordItems, Set workTaskItems, Set employeeInfos) {
		this.departmentName = departmentName;
		this.departmentDesc = departmentDesc;
		this.contractReviewRecordItems = contractReviewRecordItems;
		this.workTaskItems = workTaskItems;
		this.employeeInfos = employeeInfos;
	}

	public Integer getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(Integer departmentId) {
		this.departmentId = departmentId;
	}

	public String getDepartmentName() {
		return this.departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	public String getDepartmentDesc() {
		return this.departmentDesc;
	}

	public void setDepartmentDesc(String departmentDesc) {
		this.departmentDesc = departmentDesc;
	}

	public Set getContractReviewRecordItems() {
		return this.contractReviewRecordItems;
	}

	public void setContractReviewRecordItems(Set contractReviewRecordItems) {
		this.contractReviewRecordItems = contractReviewRecordItems;
	}

	public Set getWorkTaskItems() {
		return this.workTaskItems;
	}

	public void setWorkTaskItems(Set workTaskItems) {
		this.workTaskItems = workTaskItems;
	}

	public Set getEmployeeInfos() {
		return this.employeeInfos;
	}

	public void setEmployeeInfos(Set employeeInfos) {
		this.employeeInfos = employeeInfos;
	}

}
