package edu.tongji.anliantest.model;

// Generated 2014-9-30 13:52:24 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * EmployeeInfo generated by hbm2java
 */
public class EmployeeInfo implements java.io.Serializable {

	private Integer employeeId;
	private DepartmentInfo departmentInfo;
	private String employeeNumber;
	private String employeeName;
	private String employeePassword;
	private String employeeTitle;
	private String employeeAvatar;
	private String companyProductionProcess;
	private Set testReportTablesForSignerId = new HashSet(0);
	private Set testReportTablesForPreparerId = new HashSet(0);
	private Set projectInfosForBusinessEmployeeId = new HashSet(0);
	private Set consumerResourceItemsForResourceReturnerId = new HashSet(0);
	private Set testDataProcessTablesForReviewerId = new HashSet(0);
	private Set taskInfos = new HashSet(0);
	private Set projectInfosForProjectEmployeeId = new HashSet(0);
	private Set workTaskTables = new HashSet(0);
	private Set contractReviewRecordTables = new HashSet(0);
	private Set testDataProcessTablesForCalculaterId = new HashSet(0);
	private Set samplePlanTablesForPlanReviewEmployeeId = new HashSet(0);
	private Set consumerResourceItemsForResourceReceiverId = new HashSet(0);
	private Set testReportTablesForReviewerId = new HashSet(0);
	private Set samplePlanTablesForPlanWriteEmployeeId = new HashSet(0);

	public EmployeeInfo() {
	}

	public EmployeeInfo(String employeeNumber, String employeeName,
			String employeePassword) {
		this.employeeNumber = employeeNumber;
		this.employeeName = employeeName;
		this.employeePassword = employeePassword;
	}

	public EmployeeInfo(DepartmentInfo departmentInfo, String employeeNumber,
			String employeeName, String employeePassword, String employeeTitle,
			String employeeAvatar, String companyProductionProcess,
			Set testReportTablesForSignerId, Set testReportTablesForPreparerId,
			Set projectInfosForBusinessEmployeeId,
			Set consumerResourceItemsForResourceReturnerId,
			Set testDataProcessTablesForReviewerId, Set taskInfos,
			Set projectInfosForProjectEmployeeId, Set workTaskTables,
			Set contractReviewRecordTables,
			Set testDataProcessTablesForCalculaterId,
			Set samplePlanTablesForPlanReviewEmployeeId,
			Set consumerResourceItemsForResourceReceiverId,
			Set testReportTablesForReviewerId,
			Set samplePlanTablesForPlanWriteEmployeeId) {
		this.departmentInfo = departmentInfo;
		this.employeeNumber = employeeNumber;
		this.employeeName = employeeName;
		this.employeePassword = employeePassword;
		this.employeeTitle = employeeTitle;
		this.employeeAvatar = employeeAvatar;
		this.companyProductionProcess = companyProductionProcess;
		this.testReportTablesForSignerId = testReportTablesForSignerId;
		this.testReportTablesForPreparerId = testReportTablesForPreparerId;
		this.projectInfosForBusinessEmployeeId = projectInfosForBusinessEmployeeId;
		this.consumerResourceItemsForResourceReturnerId = consumerResourceItemsForResourceReturnerId;
		this.testDataProcessTablesForReviewerId = testDataProcessTablesForReviewerId;
		this.taskInfos = taskInfos;
		this.projectInfosForProjectEmployeeId = projectInfosForProjectEmployeeId;
		this.workTaskTables = workTaskTables;
		this.contractReviewRecordTables = contractReviewRecordTables;
		this.testDataProcessTablesForCalculaterId = testDataProcessTablesForCalculaterId;
		this.samplePlanTablesForPlanReviewEmployeeId = samplePlanTablesForPlanReviewEmployeeId;
		this.consumerResourceItemsForResourceReceiverId = consumerResourceItemsForResourceReceiverId;
		this.testReportTablesForReviewerId = testReportTablesForReviewerId;
		this.samplePlanTablesForPlanWriteEmployeeId = samplePlanTablesForPlanWriteEmployeeId;
	}

	public Integer getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(Integer employeeId) {
		this.employeeId = employeeId;
	}

	public DepartmentInfo getDepartmentInfo() {
		return this.departmentInfo;
	}

	public void setDepartmentInfo(DepartmentInfo departmentInfo) {
		this.departmentInfo = departmentInfo;
	}

	public String getEmployeeNumber() {
		return this.employeeNumber;
	}

	public void setEmployeeNumber(String employeeNumber) {
		this.employeeNumber = employeeNumber;
	}

	public String getEmployeeName() {
		return this.employeeName;
	}

	public void setEmployeeName(String employeeName) {
		this.employeeName = employeeName;
	}

	public String getEmployeePassword() {
		return this.employeePassword;
	}

	public void setEmployeePassword(String employeePassword) {
		this.employeePassword = employeePassword;
	}

	public String getEmployeeTitle() {
		return this.employeeTitle;
	}

	public void setEmployeeTitle(String employeeTitle) {
		this.employeeTitle = employeeTitle;
	}

	public String getEmployeeAvatar() {
		return this.employeeAvatar;
	}

	public void setEmployeeAvatar(String employeeAvatar) {
		this.employeeAvatar = employeeAvatar;
	}

	public String getCompanyProductionProcess() {
		return this.companyProductionProcess;
	}

	public void setCompanyProductionProcess(String companyProductionProcess) {
		this.companyProductionProcess = companyProductionProcess;
	}

	public Set getTestReportTablesForSignerId() {
		return this.testReportTablesForSignerId;
	}

	public void setTestReportTablesForSignerId(Set testReportTablesForSignerId) {
		this.testReportTablesForSignerId = testReportTablesForSignerId;
	}

	public Set getTestReportTablesForPreparerId() {
		return this.testReportTablesForPreparerId;
	}

	public void setTestReportTablesForPreparerId(
			Set testReportTablesForPreparerId) {
		this.testReportTablesForPreparerId = testReportTablesForPreparerId;
	}

	public Set getProjectInfosForBusinessEmployeeId() {
		return this.projectInfosForBusinessEmployeeId;
	}

	public void setProjectInfosForBusinessEmployeeId(
			Set projectInfosForBusinessEmployeeId) {
		this.projectInfosForBusinessEmployeeId = projectInfosForBusinessEmployeeId;
	}

	public Set getConsumerResourceItemsForResourceReturnerId() {
		return this.consumerResourceItemsForResourceReturnerId;
	}

	public void setConsumerResourceItemsForResourceReturnerId(
			Set consumerResourceItemsForResourceReturnerId) {
		this.consumerResourceItemsForResourceReturnerId = consumerResourceItemsForResourceReturnerId;
	}

	public Set getTestDataProcessTablesForReviewerId() {
		return this.testDataProcessTablesForReviewerId;
	}

	public void setTestDataProcessTablesForReviewerId(
			Set testDataProcessTablesForReviewerId) {
		this.testDataProcessTablesForReviewerId = testDataProcessTablesForReviewerId;
	}

	public Set getTaskInfos() {
		return this.taskInfos;
	}

	public void setTaskInfos(Set taskInfos) {
		this.taskInfos = taskInfos;
	}

	public Set getProjectInfosForProjectEmployeeId() {
		return this.projectInfosForProjectEmployeeId;
	}

	public void setProjectInfosForProjectEmployeeId(
			Set projectInfosForProjectEmployeeId) {
		this.projectInfosForProjectEmployeeId = projectInfosForProjectEmployeeId;
	}

	public Set getWorkTaskTables() {
		return this.workTaskTables;
	}

	public void setWorkTaskTables(Set workTaskTables) {
		this.workTaskTables = workTaskTables;
	}

	public Set getContractReviewRecordTables() {
		return this.contractReviewRecordTables;
	}

	public void setContractReviewRecordTables(Set contractReviewRecordTables) {
		this.contractReviewRecordTables = contractReviewRecordTables;
	}

	public Set getTestDataProcessTablesForCalculaterId() {
		return this.testDataProcessTablesForCalculaterId;
	}

	public void setTestDataProcessTablesForCalculaterId(
			Set testDataProcessTablesForCalculaterId) {
		this.testDataProcessTablesForCalculaterId = testDataProcessTablesForCalculaterId;
	}

	public Set getSamplePlanTablesForPlanReviewEmployeeId() {
		return this.samplePlanTablesForPlanReviewEmployeeId;
	}

	public void setSamplePlanTablesForPlanReviewEmployeeId(
			Set samplePlanTablesForPlanReviewEmployeeId) {
		this.samplePlanTablesForPlanReviewEmployeeId = samplePlanTablesForPlanReviewEmployeeId;
	}

	public Set getConsumerResourceItemsForResourceReceiverId() {
		return this.consumerResourceItemsForResourceReceiverId;
	}

	public void setConsumerResourceItemsForResourceReceiverId(
			Set consumerResourceItemsForResourceReceiverId) {
		this.consumerResourceItemsForResourceReceiverId = consumerResourceItemsForResourceReceiverId;
	}

	public Set getTestReportTablesForReviewerId() {
		return this.testReportTablesForReviewerId;
	}

	public void setTestReportTablesForReviewerId(
			Set testReportTablesForReviewerId) {
		this.testReportTablesForReviewerId = testReportTablesForReviewerId;
	}

	public Set getSamplePlanTablesForPlanWriteEmployeeId() {
		return this.samplePlanTablesForPlanWriteEmployeeId;
	}

	public void setSamplePlanTablesForPlanWriteEmployeeId(
			Set samplePlanTablesForPlanWriteEmployeeId) {
		this.samplePlanTablesForPlanWriteEmployeeId = samplePlanTablesForPlanWriteEmployeeId;
	}

}
