package edu.tongji.anliantest.model;

// Generated 2014-9-30 13:52:24 by Hibernate Tools 3.4.0.CR1

/**
 * FieldSurveyProductItem generated by hbm2java
 */
public class FieldSurveyProductItem implements java.io.Serializable {

	private Integer itemId;
	private FieldSurveyTable fieldSurveyTable;
	private String productName;
	private Integer productOutput;

	public FieldSurveyProductItem() {
	}

	public FieldSurveyProductItem(FieldSurveyTable fieldSurveyTable,
			String productName, Integer productOutput) {
		this.fieldSurveyTable = fieldSurveyTable;
		this.productName = productName;
		this.productOutput = productOutput;
	}

	public Integer getItemId() {
		return this.itemId;
	}

	public void setItemId(Integer itemId) {
		this.itemId = itemId;
	}

	public FieldSurveyTable getFieldSurveyTable() {
		return this.fieldSurveyTable;
	}

	public void setFieldSurveyTable(FieldSurveyTable fieldSurveyTable) {
		this.fieldSurveyTable = fieldSurveyTable;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public Integer getProductOutput() {
		return this.productOutput;
	}

	public void setProductOutput(Integer productOutput) {
		this.productOutput = productOutput;
	}

}
