package edu.tongji.anliantest.model;

// Generated 2014-9-30 13:52:24 by Hibernate Tools 3.4.0.CR1

/**
 * FieldSurveyContactItem generated by hbm2java
 */
public class FieldSurveyContactItem implements java.io.Serializable {

	private Integer itemId;
	private FieldSurveyTable fieldSurveyTable;
	private String personName;
	private String personDepartment;

	public FieldSurveyContactItem() {
	}

	public FieldSurveyContactItem(FieldSurveyTable fieldSurveyTable,
			String personName, String personDepartment) {
		this.fieldSurveyTable = fieldSurveyTable;
		this.personName = personName;
		this.personDepartment = personDepartment;
	}

	public Integer getItemId() {
		return this.itemId;
	}

	public void setItemId(Integer itemId) {
		this.itemId = itemId;
	}

	public FieldSurveyTable getFieldSurveyTable() {
		return this.fieldSurveyTable;
	}

	public void setFieldSurveyTable(FieldSurveyTable fieldSurveyTable) {
		this.fieldSurveyTable = fieldSurveyTable;
	}

	public String getPersonName() {
		return this.personName;
	}

	public void setPersonName(String personName) {
		this.personName = personName;
	}

	public String getPersonDepartment() {
		return this.personDepartment;
	}

	public void setPersonDepartment(String personDepartment) {
		this.personDepartment = personDepartment;
	}

}
