package edu.tongji.anliantest.model;
// Generated 2014-9-30 13:52:24 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FieldSurveyTable generated by hbm2java
 */
public class FieldSurveyTable  implements java.io.Serializable {


     private Integer tableId;
     private TableFile tableFile;
     private ProjectInfo projectInfo;
     private String tableNum;
     private Date surveyTime;
     private String companyType;
     private String companyIndustry;
     private Integer companyManagerNum;
     private Integer companyEmployeeNum;
     private Boolean companySanitationIsExist;
     private String companySanitationName;
     private Integer companySanitationNum;
     private String companyProvideResource;
     private String companyProductionProcess;
     private String companySourceList;
     private Set fieldSurveyProductItems = new HashSet(0);
     private Set fieldSurveyContactItems = new HashSet(0);

    public FieldSurveyTable() {
    }

    public FieldSurveyTable(TableFile tableFile, ProjectInfo projectInfo, String tableNum, Date surveyTime, String companyType, String companyIndustry, Integer companyManagerNum, Integer companyEmployeeNum, Boolean companySanitationIsExist, String companySanitationName, Integer companySanitationNum, String companyProvideResource, String companyProductionProcess, String companySourceList, Set fieldSurveyProductItems, Set fieldSurveyContactItems) {
       this.tableFile = tableFile;
       this.projectInfo = projectInfo;
       this.tableNum = tableNum;
       this.surveyTime = surveyTime;
       this.companyType = companyType;
       this.companyIndustry = companyIndustry;
       this.companyManagerNum = companyManagerNum;
       this.companyEmployeeNum = companyEmployeeNum;
       this.companySanitationIsExist = companySanitationIsExist;
       this.companySanitationName = companySanitationName;
       this.companySanitationNum = companySanitationNum;
       this.companyProvideResource = companyProvideResource;
       this.companyProductionProcess = companyProductionProcess;
       this.companySourceList = companySourceList;
       this.fieldSurveyProductItems = fieldSurveyProductItems;
       this.fieldSurveyContactItems = fieldSurveyContactItems;
    }
   
    public Integer getTableId() {
        return this.tableId;
    }
    
    public void setTableId(Integer tableId) {
        this.tableId = tableId;
    }
    public TableFile getTableFile() {
        return this.tableFile;
    }
    
    public void setTableFile(TableFile tableFile) {
        this.tableFile = tableFile;
    }
    public ProjectInfo getProjectInfo() {
        return this.projectInfo;
    }
    
    public void setProjectInfo(ProjectInfo projectInfo) {
        this.projectInfo = projectInfo;
    }
    public String getTableNum() {
        return this.tableNum;
    }
    
    public void setTableNum(String tableNum) {
        this.tableNum = tableNum;
    }
    public Date getSurveyTime() {
        return this.surveyTime;
    }
    
    public void setSurveyTime(Date surveyTime) {
        this.surveyTime = surveyTime;
    }
    public String getCompanyType() {
        return this.companyType;
    }
    
    public void setCompanyType(String companyType) {
        this.companyType = companyType;
    }
    public String getCompanyIndustry() {
        return this.companyIndustry;
    }
    
    public void setCompanyIndustry(String companyIndustry) {
        this.companyIndustry = companyIndustry;
    }
    public Integer getCompanyManagerNum() {
        return this.companyManagerNum;
    }
    
    public void setCompanyManagerNum(Integer companyManagerNum) {
        this.companyManagerNum = companyManagerNum;
    }
    public Integer getCompanyEmployeeNum() {
        return this.companyEmployeeNum;
    }
    
    public void setCompanyEmployeeNum(Integer companyEmployeeNum) {
        this.companyEmployeeNum = companyEmployeeNum;
    }
    public Boolean getCompanySanitationIsExist() {
        return this.companySanitationIsExist;
    }
    
    public void setCompanySanitationIsExist(Boolean companySanitationIsExist) {
        this.companySanitationIsExist = companySanitationIsExist;
    }
    public String getCompanySanitationName() {
        return this.companySanitationName;
    }
    
    public void setCompanySanitationName(String companySanitationName) {
        this.companySanitationName = companySanitationName;
    }
    public Integer getCompanySanitationNum() {
        return this.companySanitationNum;
    }
    
    public void setCompanySanitationNum(Integer companySanitationNum) {
        this.companySanitationNum = companySanitationNum;
    }
    public String getCompanyProvideResource() {
        return this.companyProvideResource;
    }
    
    public void setCompanyProvideResource(String companyProvideResource) {
        this.companyProvideResource = companyProvideResource;
    }
    public String getCompanyProductionProcess() {
        return this.companyProductionProcess;
    }
    
    public void setCompanyProductionProcess(String companyProductionProcess) {
        this.companyProductionProcess = companyProductionProcess;
    }
    public String getCompanySourceList() {
        return this.companySourceList;
    }
    
    public void setCompanySourceList(String companySourceList) {
        this.companySourceList = companySourceList;
    }
    public Set getFieldSurveyProductItems() {
        return this.fieldSurveyProductItems;
    }
    
    public void setFieldSurveyProductItems(Set fieldSurveyProductItems) {
        this.fieldSurveyProductItems = fieldSurveyProductItems;
    }
    public Set getFieldSurveyContactItems() {
        return this.fieldSurveyContactItems;
    }
    
    public void setFieldSurveyContactItems(Set fieldSurveyContactItems) {
        this.fieldSurveyContactItems = fieldSurveyContactItems;
    }




}


