package edu.tongji.anliantest.model;

// Generated 2014-9-30 13:52:24 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * HarmfulSubstanceNationalStandardTable generated by hbm2java
 */
public class HarmfulSubstanceNationalStandardTable implements
		java.io.Serializable {

	private int substanceId;
	private String substanceEnglishName;
	private String substanceChineseName;
	private String chemicalAbstractNum;
	private BigDecimal mac;
	private BigDecimal pcTwa;
	private BigDecimal pcStel;
	private BigDecimal om;
	private String substanceComment;
	private Integer macScale;
	private Integer pcTwaScale;
	private Integer pcStelScale;
	private Integer omScale;
	private Set testReportItems = new HashSet(0);
	private Set testDataResultItems = new HashSet(0);
	private Set samplePlanItems = new HashSet(0);
	private Set testDataProcessGroups = new HashSet(0);

	public HarmfulSubstanceNationalStandardTable() {
	}

	public HarmfulSubstanceNationalStandardTable(int substanceId) {
		this.substanceId = substanceId;
	}

	public HarmfulSubstanceNationalStandardTable(int substanceId,
			String substanceEnglishName, String substanceChineseName,
			String chemicalAbstractNum, BigDecimal mac, BigDecimal pcTwa,
			BigDecimal pcStel, BigDecimal om, String substanceComment,
			Integer macScale, Integer pcTwaScale, Integer pcStelScale,
			Integer omScale, Set testReportItems, Set testDataResultItems,
			Set samplePlanItems, Set testDataProcessGroups) {
		this.substanceId = substanceId;
		this.substanceEnglishName = substanceEnglishName;
		this.substanceChineseName = substanceChineseName;
		this.chemicalAbstractNum = chemicalAbstractNum;
		this.mac = mac;
		this.pcTwa = pcTwa;
		this.pcStel = pcStel;
		this.om = om;
		this.substanceComment = substanceComment;
		this.macScale = macScale;
		this.pcTwaScale = pcTwaScale;
		this.pcStelScale = pcStelScale;
		this.omScale = omScale;
		this.testReportItems = testReportItems;
		this.testDataResultItems = testDataResultItems;
		this.samplePlanItems = samplePlanItems;
		this.testDataProcessGroups = testDataProcessGroups;
	}

	public int getSubstanceId() {
		return this.substanceId;
	}

	public void setSubstanceId(int substanceId) {
		this.substanceId = substanceId;
	}

	public String getSubstanceEnglishName() {
		return this.substanceEnglishName;
	}

	public void setSubstanceEnglishName(String substanceEnglishName) {
		this.substanceEnglishName = substanceEnglishName;
	}

	public String getSubstanceChineseName() {
		return this.substanceChineseName;
	}

	public void setSubstanceChineseName(String substanceChineseName) {
		this.substanceChineseName = substanceChineseName;
	}

	public String getChemicalAbstractNum() {
		return this.chemicalAbstractNum;
	}

	public void setChemicalAbstractNum(String chemicalAbstractNum) {
		this.chemicalAbstractNum = chemicalAbstractNum;
	}

	public BigDecimal getMac() {
		return this.mac;
	}

	public void setMac(BigDecimal mac) {
		this.mac = mac;
	}

	public BigDecimal getPcTwa() {
		return this.pcTwa;
	}

	public void setPcTwa(BigDecimal pcTwa) {
		this.pcTwa = pcTwa;
	}

	public BigDecimal getPcStel() {
		return this.pcStel;
	}

	public void setPcStel(BigDecimal pcStel) {
		this.pcStel = pcStel;
	}

	public BigDecimal getOm() {
		return this.om;
	}

	public void setOm(BigDecimal om) {
		this.om = om;
	}

	public String getSubstanceComment() {
		return this.substanceComment;
	}

	public void setSubstanceComment(String substanceComment) {
		this.substanceComment = substanceComment;
	}

	public Integer getMacScale() {
		return this.macScale;
	}

	public void setMacScale(Integer macScale) {
		this.macScale = macScale;
	}

	public Integer getPcTwaScale() {
		return this.pcTwaScale;
	}

	public void setPcTwaScale(Integer pcTwaScale) {
		this.pcTwaScale = pcTwaScale;
	}

	public Integer getPcStelScale() {
		return this.pcStelScale;
	}

	public void setPcStelScale(Integer pcStelScale) {
		this.pcStelScale = pcStelScale;
	}

	public Integer getOmScale() {
		return this.omScale;
	}

	public void setOmScale(Integer omScale) {
		this.omScale = omScale;
	}

	public Set getTestReportItems() {
		return this.testReportItems;
	}

	public void setTestReportItems(Set testReportItems) {
		this.testReportItems = testReportItems;
	}

	public Set getTestDataResultItems() {
		return this.testDataResultItems;
	}

	public void setTestDataResultItems(Set testDataResultItems) {
		this.testDataResultItems = testDataResultItems;
	}

	public Set getSamplePlanItems() {
		return this.samplePlanItems;
	}

	public void setSamplePlanItems(Set samplePlanItems) {
		this.samplePlanItems = samplePlanItems;
	}

	public Set getTestDataProcessGroups() {
		return this.testDataProcessGroups;
	}

	public void setTestDataProcessGroups(Set testDataProcessGroups) {
		this.testDataProcessGroups = testDataProcessGroups;
	}

}
