package edu.tongji.anliantest.model;

// Generated 2014-9-30 13:52:24 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ProjectInfo generated by hbm2java
 */
public class ProjectInfo implements java.io.Serializable {

	private Integer projectId;
	private EmployeeInfo employeeInfoByProjectEmployeeId;
	private EmployeeInfo employeeInfoByBusinessEmployeeId;
	private String projectNum;
	private String projectName;
	private String projectType;
	private Date projectCreateTime;
	private String projectStatus;
	private String companyName;
	private String companyAddress;
	private String contactPerson;
	private String contactTel;
	private Integer contractAmount;
	private Set samplePlanTables = new HashSet(0);
	private Set workTaskTables = new HashSet(0);
	private Set contractReviewRecordTables = new HashSet(0);
	private Set testDataResultTables = new HashSet(0);
	private Set testDataProcessTables = new HashSet(0);
	private Set testReportTables = new HashSet(0);
	private Set fieldSurveyTables = new HashSet(0);
	private Set consumerResourceTables = new HashSet(0);
	private Set taskInfos = new HashSet(0);

	public ProjectInfo() {
	}

	public ProjectInfo(EmployeeInfo employeeInfoByProjectEmployeeId,
			EmployeeInfo employeeInfoByBusinessEmployeeId, String projectNum,
			String projectName, String projectType, Date projectCreateTime,
			String projectStatus, String companyName, String companyAddress,
			String contactPerson, String contactTel, Integer contractAmount,
			Set samplePlanTables, Set workTaskTables,
			Set contractReviewRecordTables, Set testDataResultTables,
			Set testDataProcessTables, Set testReportTables,
			Set fieldSurveyTables, Set consumerResourceTables, Set taskInfos) {
		this.employeeInfoByProjectEmployeeId = employeeInfoByProjectEmployeeId;
		this.employeeInfoByBusinessEmployeeId = employeeInfoByBusinessEmployeeId;
		this.projectNum = projectNum;
		this.projectName = projectName;
		this.projectType = projectType;
		this.projectCreateTime = projectCreateTime;
		this.projectStatus = projectStatus;
		this.companyName = companyName;
		this.companyAddress = companyAddress;
		this.contactPerson = contactPerson;
		this.contactTel = contactTel;
		this.contractAmount = contractAmount;
		this.samplePlanTables = samplePlanTables;
		this.workTaskTables = workTaskTables;
		this.contractReviewRecordTables = contractReviewRecordTables;
		this.testDataResultTables = testDataResultTables;
		this.testDataProcessTables = testDataProcessTables;
		this.testReportTables = testReportTables;
		this.fieldSurveyTables = fieldSurveyTables;
		this.consumerResourceTables = consumerResourceTables;
		this.taskInfos = taskInfos;
	}

	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	public EmployeeInfo getEmployeeInfoByProjectEmployeeId() {
		return this.employeeInfoByProjectEmployeeId;
	}

	public void setEmployeeInfoByProjectEmployeeId(
			EmployeeInfo employeeInfoByProjectEmployeeId) {
		this.employeeInfoByProjectEmployeeId = employeeInfoByProjectEmployeeId;
	}

	public EmployeeInfo getEmployeeInfoByBusinessEmployeeId() {
		return this.employeeInfoByBusinessEmployeeId;
	}

	public void setEmployeeInfoByBusinessEmployeeId(
			EmployeeInfo employeeInfoByBusinessEmployeeId) {
		this.employeeInfoByBusinessEmployeeId = employeeInfoByBusinessEmployeeId;
	}

	public String getProjectNum() {
		return this.projectNum;
	}

	public void setProjectNum(String projectNum) {
		this.projectNum = projectNum;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public String getProjectType() {
		return this.projectType;
	}

	public void setProjectType(String projectType) {
		this.projectType = projectType;
	}

	public Date getProjectCreateTime() {
		return this.projectCreateTime;
	}

	public void setProjectCreateTime(Date projectCreateTime) {
		this.projectCreateTime = projectCreateTime;
	}

	public String getProjectStatus() {
		return this.projectStatus;
	}

	public void setProjectStatus(String projectStatus) {
		this.projectStatus = projectStatus;
	}

	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public String getCompanyAddress() {
		return this.companyAddress;
	}

	public void setCompanyAddress(String companyAddress) {
		this.companyAddress = companyAddress;
	}

	public String getContactPerson() {
		return this.contactPerson;
	}

	public void setContactPerson(String contactPerson) {
		this.contactPerson = contactPerson;
	}

	public String getContactTel() {
		return this.contactTel;
	}

	public void setContactTel(String contactTel) {
		this.contactTel = contactTel;
	}

	public Integer getContractAmount() {
		return this.contractAmount;
	}

	public void setContractAmount(Integer contractAmount) {
		this.contractAmount = contractAmount;
	}

	public Set getSamplePlanTables() {
		return this.samplePlanTables;
	}

	public void setSamplePlanTables(Set samplePlanTables) {
		this.samplePlanTables = samplePlanTables;
	}

	public Set getWorkTaskTables() {
		return this.workTaskTables;
	}

	public void setWorkTaskTables(Set workTaskTables) {
		this.workTaskTables = workTaskTables;
	}

	public Set getContractReviewRecordTables() {
		return this.contractReviewRecordTables;
	}

	public void setContractReviewRecordTables(Set contractReviewRecordTables) {
		this.contractReviewRecordTables = contractReviewRecordTables;
	}

	public Set getTestDataResultTables() {
		return this.testDataResultTables;
	}

	public void setTestDataResultTables(Set testDataResultTables) {
		this.testDataResultTables = testDataResultTables;
	}

	public Set getTestDataProcessTables() {
		return this.testDataProcessTables;
	}

	public void setTestDataProcessTables(Set testDataProcessTables) {
		this.testDataProcessTables = testDataProcessTables;
	}

	public Set getTestReportTables() {
		return this.testReportTables;
	}

	public void setTestReportTables(Set testReportTables) {
		this.testReportTables = testReportTables;
	}

	public Set getFieldSurveyTables() {
		return this.fieldSurveyTables;
	}

	public void setFieldSurveyTables(Set fieldSurveyTables) {
		this.fieldSurveyTables = fieldSurveyTables;
	}

	public Set getConsumerResourceTables() {
		return this.consumerResourceTables;
	}

	public void setConsumerResourceTables(Set consumerResourceTables) {
		this.consumerResourceTables = consumerResourceTables;
	}

	public Set getTaskInfos() {
		return this.taskInfos;
	}

	public void setTaskInfos(Set taskInfos) {
		this.taskInfos = taskInfos;
	}

}
