package edu.tongji.anliantest.model;

// Generated 2014-9-30 13:52:24 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * SamplePlanItem generated by hbm2java
 */
public class SamplePlanItem implements java.io.Serializable {

	private Integer itemId;
	private HarmfulSubstanceNationalStandardTable harmfulSubstanceNationalStandardTable;
	private SamplePlanTable samplePlanTable;
	private String sampleWorkshopJob;
	private Integer sampleDeviceId;
	private String sampleDeviceName;
	private String sampleStandard;
	private BigDecimal sampleTime;
	private BigDecimal sampleFlow;
	private Integer collectDeviceId;
	private String collectDeviceName;
	private Integer sampleCount;
	private String sampleNum;
	private String sampleSaveMethod;
	private String sampleComment;

	public SamplePlanItem() {
	}

	public SamplePlanItem(
			HarmfulSubstanceNationalStandardTable harmfulSubstanceNationalStandardTable,
			SamplePlanTable samplePlanTable, String sampleWorkshopJob,
			Integer sampleDeviceId, String sampleDeviceName,
			String sampleStandard, BigDecimal sampleTime,
			BigDecimal sampleFlow, Integer collectDeviceId,
			String collectDeviceName, Integer sampleCount, String sampleNum,
			String sampleSaveMethod, String sampleComment) {
		this.harmfulSubstanceNationalStandardTable = harmfulSubstanceNationalStandardTable;
		this.samplePlanTable = samplePlanTable;
		this.sampleWorkshopJob = sampleWorkshopJob;
		this.sampleDeviceId = sampleDeviceId;
		this.sampleDeviceName = sampleDeviceName;
		this.sampleStandard = sampleStandard;
		this.sampleTime = sampleTime;
		this.sampleFlow = sampleFlow;
		this.collectDeviceId = collectDeviceId;
		this.collectDeviceName = collectDeviceName;
		this.sampleCount = sampleCount;
		this.sampleNum = sampleNum;
		this.sampleSaveMethod = sampleSaveMethod;
		this.sampleComment = sampleComment;
	}

	public Integer getItemId() {
		return this.itemId;
	}

	public void setItemId(Integer itemId) {
		this.itemId = itemId;
	}

	public HarmfulSubstanceNationalStandardTable getHarmfulSubstanceNationalStandardTable() {
		return this.harmfulSubstanceNationalStandardTable;
	}

	public void setHarmfulSubstanceNationalStandardTable(
			HarmfulSubstanceNationalStandardTable harmfulSubstanceNationalStandardTable) {
		this.harmfulSubstanceNationalStandardTable = harmfulSubstanceNationalStandardTable;
	}

	public SamplePlanTable getSamplePlanTable() {
		return this.samplePlanTable;
	}

	public void setSamplePlanTable(SamplePlanTable samplePlanTable) {
		this.samplePlanTable = samplePlanTable;
	}

	public String getSampleWorkshopJob() {
		return this.sampleWorkshopJob;
	}

	public void setSampleWorkshopJob(String sampleWorkshopJob) {
		this.sampleWorkshopJob = sampleWorkshopJob;
	}

	public Integer getSampleDeviceId() {
		return this.sampleDeviceId;
	}

	public void setSampleDeviceId(Integer sampleDeviceId) {
		this.sampleDeviceId = sampleDeviceId;
	}

	public String getSampleDeviceName() {
		return this.sampleDeviceName;
	}

	public void setSampleDeviceName(String sampleDeviceName) {
		this.sampleDeviceName = sampleDeviceName;
	}

	public String getSampleStandard() {
		return this.sampleStandard;
	}

	public void setSampleStandard(String sampleStandard) {
		this.sampleStandard = sampleStandard;
	}

	public BigDecimal getSampleTime() {
		return this.sampleTime;
	}

	public void setSampleTime(BigDecimal sampleTime) {
		this.sampleTime = sampleTime;
	}

	public BigDecimal getSampleFlow() {
		return this.sampleFlow;
	}

	public void setSampleFlow(BigDecimal sampleFlow) {
		this.sampleFlow = sampleFlow;
	}

	public Integer getCollectDeviceId() {
		return this.collectDeviceId;
	}

	public void setCollectDeviceId(Integer collectDeviceId) {
		this.collectDeviceId = collectDeviceId;
	}

	public String getCollectDeviceName() {
		return this.collectDeviceName;
	}

	public void setCollectDeviceName(String collectDeviceName) {
		this.collectDeviceName = collectDeviceName;
	}

	public Integer getSampleCount() {
		return this.sampleCount;
	}

	public void setSampleCount(Integer sampleCount) {
		this.sampleCount = sampleCount;
	}

	public String getSampleNum() {
		return this.sampleNum;
	}

	public void setSampleNum(String sampleNum) {
		this.sampleNum = sampleNum;
	}

	public String getSampleSaveMethod() {
		return this.sampleSaveMethod;
	}

	public void setSampleSaveMethod(String sampleSaveMethod) {
		this.sampleSaveMethod = sampleSaveMethod;
	}

	public String getSampleComment() {
		return this.sampleComment;
	}

	public void setSampleComment(String sampleComment) {
		this.sampleComment = sampleComment;
	}

}
