package edu.tongji.anliantest.model;

// Generated 2014-9-30 13:52:24 by Hibernate Tools 3.4.0.CR1

/**
 * SystemRole generated by hbm2java
 */
public class SystemRole implements java.io.Serializable {

	private Integer roleId;
	private String roleName;

	public SystemRole() {
	}

	public SystemRole(String roleName) {
		this.roleName = roleName;
	}

	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

}
