package edu.tongji.anliantest.model;

// Generated 2014-9-30 13:52:24 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TableFile generated by hbm2java
 */
public class TableFile implements java.io.Serializable {

	private Integer fileId;
	private String fileUrl;
	private String fileName;
	private Set fieldSurveyTables = new HashSet(0);

	public TableFile() {
	}

	public TableFile(String fileUrl, String fileName, Set fieldSurveyTables) {
		this.fileUrl = fileUrl;
		this.fileName = fileName;
		this.fieldSurveyTables = fieldSurveyTables;
	}

	public Integer getFileId() {
		return this.fileId;
	}

	public void setFileId(Integer fileId) {
		this.fileId = fileId;
	}

	public String getFileUrl() {
		return this.fileUrl;
	}

	public void setFileUrl(String fileUrl) {
		this.fileUrl = fileUrl;
	}

	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public Set getFieldSurveyTables() {
		return this.fieldSurveyTables;
	}

	public void setFieldSurveyTables(Set fieldSurveyTables) {
		this.fieldSurveyTables = fieldSurveyTables;
	}

}
