package edu.tongji.anliantest.model;

// Generated 2014-9-30 13:52:24 by Hibernate Tools 3.4.0.CR1

/**
 * TaskInfo generated by hbm2java
 */
public class TaskInfo implements java.io.Serializable {

	private Integer taskId;
	private EmployeeInfo employeeInfo;
	private ProjectInfo projectInfo;
	private String taskType;
	private Integer taskStatus;

	public TaskInfo() {
	}

	public TaskInfo(EmployeeInfo employeeInfo, ProjectInfo projectInfo,
			String taskType, Integer taskStatus) {
		this.employeeInfo = employeeInfo;
		this.projectInfo = projectInfo;
		this.taskType = taskType;
		this.taskStatus = taskStatus;
	}

	public Integer getTaskId() {
		return this.taskId;
	}

	public void setTaskId(Integer taskId) {
		this.taskId = taskId;
	}

	public EmployeeInfo getEmployeeInfo() {
		return this.employeeInfo;
	}

	public void setEmployeeInfo(EmployeeInfo employeeInfo) {
		this.employeeInfo = employeeInfo;
	}

	public ProjectInfo getProjectInfo() {
		return this.projectInfo;
	}

	public void setProjectInfo(ProjectInfo projectInfo) {
		this.projectInfo = projectInfo;
	}

	public String getTaskType() {
		return this.taskType;
	}

	public void setTaskType(String taskType) {
		this.taskType = taskType;
	}

	public Integer getTaskStatus() {
		return this.taskStatus;
	}

	public void setTaskStatus(Integer taskStatus) {
		this.taskStatus = taskStatus;
	}

}
