package edu.tongji.anliantest.model;

// Generated 2014-5-5 12:47:38 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TaskInfo generated by hbm2java
 */
@Entity
@Table(name = "task_info", catalog = "anliantest")
public class TaskInfo implements java.io.Serializable {

	private Integer taskId;
	private EmployeeInfo employeeInfo;
	private ProjectInfo projectInfo;
	private String taskType;
	private Integer taskStatus;

	public TaskInfo() {
	}

	public TaskInfo(EmployeeInfo employeeInfo, ProjectInfo projectInfo,
			String taskType, Integer taskStatus) {
		this.employeeInfo = employeeInfo;
		this.projectInfo = projectInfo;
		this.taskType = taskType;
		this.taskStatus = taskStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "task_id", unique = true, nullable = false)
	public Integer getTaskId() {
		return this.taskId;
	}

	public void setTaskId(Integer taskId) {
		this.taskId = taskId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "employee_id")
	public EmployeeInfo getEmployeeInfo() {
		return this.employeeInfo;
	}

	public void setEmployeeInfo(EmployeeInfo employeeInfo) {
		this.employeeInfo = employeeInfo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id")
	public ProjectInfo getProjectInfo() {
		return this.projectInfo;
	}

	public void setProjectInfo(ProjectInfo projectInfo) {
		this.projectInfo = projectInfo;
	}

	@Column(name = "task_type", length = 100)
	public String getTaskType() {
		return this.taskType;
	}

	public void setTaskType(String taskType) {
		this.taskType = taskType;
	}

	@Column(name = "task_status")
	public Integer getTaskStatus() {
		return this.taskStatus;
	}

	public void setTaskStatus(Integer taskStatus) {
		this.taskStatus = taskStatus;
	}

}
