package edu.tongji.anliantest.model;

// Generated 2014-9-30 13:52:24 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * TestDataResultItem generated by hbm2java
 */
public class TestDataResultItem implements java.io.Serializable {

	private int itemId;
	private HarmfulSubstanceNationalStandardTable harmfulSubstanceNationalStandardTable;
	private TestDataResultTable testDataResultTable;
	private String substanceDetailedName;
	private String testWorkshopJob;
	private Integer testSampleCount;
	private BigDecimal testTouchTime;
	private BigDecimal mac;
	private BigDecimal ctwa;
	private BigDecimal cstel;
	private BigDecimal om;
	private Integer macScale;
	private Integer ctwaScale;
	private Integer cstelScale;
	private Integer omScale;
	private BigDecimal testResultRangeStart;
	private BigDecimal testResultRangeEnd;
	private String testResult;
	private Integer testResultRangeScale;
	private String resultType;
	private Integer testTouchTimeScale;
	private String testResultRangeStartType;
	private String testResultRangeEndType;

	public TestDataResultItem() {
	}

	public TestDataResultItem(int itemId) {
		this.itemId = itemId;
	}

	public TestDataResultItem(
			int itemId,
			HarmfulSubstanceNationalStandardTable harmfulSubstanceNationalStandardTable,
			TestDataResultTable testDataResultTable,
			String substanceDetailedName, String testWorkshopJob,
			Integer testSampleCount, BigDecimal testTouchTime, BigDecimal mac,
			BigDecimal ctwa, BigDecimal cstel, BigDecimal om, Integer macScale,
			Integer ctwaScale, Integer cstelScale, Integer omScale,
			BigDecimal testResultRangeStart, BigDecimal testResultRangeEnd,
			String testResult, Integer testResultRangeScale, String resultType,
			Integer testTouchTimeScale, String testResultRangeStartType,
			String testResultRangeEndType) {
		this.itemId = itemId;
		this.harmfulSubstanceNationalStandardTable = harmfulSubstanceNationalStandardTable;
		this.testDataResultTable = testDataResultTable;
		this.substanceDetailedName = substanceDetailedName;
		this.testWorkshopJob = testWorkshopJob;
		this.testSampleCount = testSampleCount;
		this.testTouchTime = testTouchTime;
		this.mac = mac;
		this.ctwa = ctwa;
		this.cstel = cstel;
		this.om = om;
		this.macScale = macScale;
		this.ctwaScale = ctwaScale;
		this.cstelScale = cstelScale;
		this.omScale = omScale;
		this.testResultRangeStart = testResultRangeStart;
		this.testResultRangeEnd = testResultRangeEnd;
		this.testResult = testResult;
		this.testResultRangeScale = testResultRangeScale;
		this.resultType = resultType;
		this.testTouchTimeScale = testTouchTimeScale;
		this.testResultRangeStartType = testResultRangeStartType;
		this.testResultRangeEndType = testResultRangeEndType;
	}

	public int getItemId() {
		return this.itemId;
	}

	public void setItemId(int itemId) {
		this.itemId = itemId;
	}

	public HarmfulSubstanceNationalStandardTable getHarmfulSubstanceNationalStandardTable() {
		return this.harmfulSubstanceNationalStandardTable;
	}

	public void setHarmfulSubstanceNationalStandardTable(
			HarmfulSubstanceNationalStandardTable harmfulSubstanceNationalStandardTable) {
		this.harmfulSubstanceNationalStandardTable = harmfulSubstanceNationalStandardTable;
	}

	public TestDataResultTable getTestDataResultTable() {
		return this.testDataResultTable;
	}

	public void setTestDataResultTable(TestDataResultTable testDataResultTable) {
		this.testDataResultTable = testDataResultTable;
	}

	public String getSubstanceDetailedName() {
		return this.substanceDetailedName;
	}

	public void setSubstanceDetailedName(String substanceDetailedName) {
		this.substanceDetailedName = substanceDetailedName;
	}

	public String getTestWorkshopJob() {
		return this.testWorkshopJob;
	}

	public void setTestWorkshopJob(String testWorkshopJob) {
		this.testWorkshopJob = testWorkshopJob;
	}

	public Integer getTestSampleCount() {
		return this.testSampleCount;
	}

	public void setTestSampleCount(Integer testSampleCount) {
		this.testSampleCount = testSampleCount;
	}

	public BigDecimal getTestTouchTime() {
		return this.testTouchTime;
	}

	public void setTestTouchTime(BigDecimal testTouchTime) {
		this.testTouchTime = testTouchTime;
	}

	public BigDecimal getMac() {
		return this.mac;
	}

	public void setMac(BigDecimal mac) {
		this.mac = mac;
	}

	public BigDecimal getCtwa() {
		return this.ctwa;
	}

	public void setCtwa(BigDecimal ctwa) {
		this.ctwa = ctwa;
	}

	public BigDecimal getCstel() {
		return this.cstel;
	}

	public void setCstel(BigDecimal cstel) {
		this.cstel = cstel;
	}

	public BigDecimal getOm() {
		return this.om;
	}

	public void setOm(BigDecimal om) {
		this.om = om;
	}

	public Integer getMacScale() {
		return this.macScale;
	}

	public void setMacScale(Integer macScale) {
		this.macScale = macScale;
	}

	public Integer getCtwaScale() {
		return this.ctwaScale;
	}

	public void setCtwaScale(Integer ctwaScale) {
		this.ctwaScale = ctwaScale;
	}

	public Integer getCstelScale() {
		return this.cstelScale;
	}

	public void setCstelScale(Integer cstelScale) {
		this.cstelScale = cstelScale;
	}

	public Integer getOmScale() {
		return this.omScale;
	}

	public void setOmScale(Integer omScale) {
		this.omScale = omScale;
	}

	public BigDecimal getTestResultRangeStart() {
		return this.testResultRangeStart;
	}

	public void setTestResultRangeStart(BigDecimal testResultRangeStart) {
		this.testResultRangeStart = testResultRangeStart;
	}

	public BigDecimal getTestResultRangeEnd() {
		return this.testResultRangeEnd;
	}

	public void setTestResultRangeEnd(BigDecimal testResultRangeEnd) {
		this.testResultRangeEnd = testResultRangeEnd;
	}

	public String getTestResult() {
		return this.testResult;
	}

	public void setTestResult(String testResult) {
		this.testResult = testResult;
	}

	public Integer getTestResultRangeScale() {
		return this.testResultRangeScale;
	}

	public void setTestResultRangeScale(Integer testResultRangeScale) {
		this.testResultRangeScale = testResultRangeScale;
	}

	public String getResultType() {
		return this.resultType;
	}

	public void setResultType(String resultType) {
		this.resultType = resultType;
	}

	public Integer getTestTouchTimeScale() {
		return this.testTouchTimeScale;
	}

	public void setTestTouchTimeScale(Integer testTouchTimeScale) {
		this.testTouchTimeScale = testTouchTimeScale;
	}

	public String getTestResultRangeStartType() {
		return this.testResultRangeStartType;
	}

	public void setTestResultRangeStartType(String testResultRangeStartType) {
		this.testResultRangeStartType = testResultRangeStartType;
	}

	public String getTestResultRangeEndType() {
		return this.testResultRangeEndType;
	}

	public void setTestResultRangeEndType(String testResultRangeEndType) {
		this.testResultRangeEndType = testResultRangeEndType;
	}

}
