package edu.tongji.anliantest.model;

// Generated 2014-9-30 13:52:24 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TestDataProcessTable generated by hbm2java
 */
public class TestDataProcessTable implements java.io.Serializable {

	private int tableId;
	private ProjectInfo projectInfo;
	private EmployeeInfo employeeInfoByReviewerId;
	private EmployeeInfo employeeInfoByCalculaterId;
	private Date calculateTime;
	private Date reviewTime;
	private String tableNum;
	private Set testDataProcessGroups = new HashSet(0);

	public TestDataProcessTable() {
	}

	public TestDataProcessTable(int tableId) {
		this.tableId = tableId;
	}

	public TestDataProcessTable(int tableId, ProjectInfo projectInfo,
			EmployeeInfo employeeInfoByReviewerId,
			EmployeeInfo employeeInfoByCalculaterId, Date calculateTime,
			Date reviewTime, String tableNum, Set testDataProcessGroups) {
		this.tableId = tableId;
		this.projectInfo = projectInfo;
		this.employeeInfoByReviewerId = employeeInfoByReviewerId;
		this.employeeInfoByCalculaterId = employeeInfoByCalculaterId;
		this.calculateTime = calculateTime;
		this.reviewTime = reviewTime;
		this.tableNum = tableNum;
		this.testDataProcessGroups = testDataProcessGroups;
	}

	public int getTableId() {
		return this.tableId;
	}

	public void setTableId(int tableId) {
		this.tableId = tableId;
	}

	public ProjectInfo getProjectInfo() {
		return this.projectInfo;
	}

	public void setProjectInfo(ProjectInfo projectInfo) {
		this.projectInfo = projectInfo;
	}

	public EmployeeInfo getEmployeeInfoByReviewerId() {
		return this.employeeInfoByReviewerId;
	}

	public void setEmployeeInfoByReviewerId(
			EmployeeInfo employeeInfoByReviewerId) {
		this.employeeInfoByReviewerId = employeeInfoByReviewerId;
	}

	public EmployeeInfo getEmployeeInfoByCalculaterId() {
		return this.employeeInfoByCalculaterId;
	}

	public void setEmployeeInfoByCalculaterId(
			EmployeeInfo employeeInfoByCalculaterId) {
		this.employeeInfoByCalculaterId = employeeInfoByCalculaterId;
	}

	public Date getCalculateTime() {
		return this.calculateTime;
	}

	public void setCalculateTime(Date calculateTime) {
		this.calculateTime = calculateTime;
	}

	public Date getReviewTime() {
		return this.reviewTime;
	}

	public void setReviewTime(Date reviewTime) {
		this.reviewTime = reviewTime;
	}

	public String getTableNum() {
		return this.tableNum;
	}

	public void setTableNum(String tableNum) {
		this.tableNum = tableNum;
	}

	public Set getTestDataProcessGroups() {
		return this.testDataProcessGroups;
	}

	public void setTestDataProcessGroups(Set testDataProcessGroups) {
		this.testDataProcessGroups = testDataProcessGroups;
	}

}
