package edu.tongji.anliantest.model;

// Generated 2014-9-30 13:52:24 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * TestDataProcessItem generated by hbm2java
 */
public class TestDataProcessItem implements java.io.Serializable {

	private int itemId;
	private TestDataProcessGroup testDataProcessGroup;
	private Integer testSampleId;
	private String testSampleNum;
	private BigDecimal testResult;
	private String testResultType;
	private BigDecimal testTouchTime;
	private Integer testTouchTimeScale;
	private Integer testResultScale;

	public TestDataProcessItem() {
	}

	public TestDataProcessItem(int itemId) {
		this.itemId = itemId;
	}

	public TestDataProcessItem(int itemId,
			TestDataProcessGroup testDataProcessGroup, Integer testSampleId,
			String testSampleNum, BigDecimal testResult, String testResultType,
			BigDecimal testTouchTime, Integer testTouchTimeScale,
			Integer testResultScale) {
		this.itemId = itemId;
		this.testDataProcessGroup = testDataProcessGroup;
		this.testSampleId = testSampleId;
		this.testSampleNum = testSampleNum;
		this.testResult = testResult;
		this.testResultType = testResultType;
		this.testTouchTime = testTouchTime;
		this.testTouchTimeScale = testTouchTimeScale;
		this.testResultScale = testResultScale;
	}

	public int getItemId() {
		return this.itemId;
	}

	public void setItemId(int itemId) {
		this.itemId = itemId;
	}

	public TestDataProcessGroup getTestDataProcessGroup() {
		return this.testDataProcessGroup;
	}

	public void setTestDataProcessGroup(
			TestDataProcessGroup testDataProcessGroup) {
		this.testDataProcessGroup = testDataProcessGroup;
	}

	public Integer getTestSampleId() {
		return this.testSampleId;
	}

	public void setTestSampleId(Integer testSampleId) {
		this.testSampleId = testSampleId;
	}

	public String getTestSampleNum() {
		return this.testSampleNum;
	}

	public void setTestSampleNum(String testSampleNum) {
		this.testSampleNum = testSampleNum;
	}

	public BigDecimal getTestResult() {
		return this.testResult;
	}

	public void setTestResult(BigDecimal testResult) {
		this.testResult = testResult;
	}

	public String getTestResultType() {
		return this.testResultType;
	}

	public void setTestResultType(String testResultType) {
		this.testResultType = testResultType;
	}

	public BigDecimal getTestTouchTime() {
		return this.testTouchTime;
	}

	public void setTestTouchTime(BigDecimal testTouchTime) {
		this.testTouchTime = testTouchTime;
	}

	public Integer getTestTouchTimeScale() {
		return this.testTouchTimeScale;
	}

	public void setTestTouchTimeScale(Integer testTouchTimeScale) {
		this.testTouchTimeScale = testTouchTimeScale;
	}

	public Integer getTestResultScale() {
		return this.testResultScale;
	}

	public void setTestResultScale(Integer testResultScale) {
		this.testResultScale = testResultScale;
	}

}
