package edu.tongji.anliantest.model;

// Generated 2014-9-30 13:52:24 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TestDataProcessGroup generated by hbm2java
 */
public class TestDataProcessGroup implements java.io.Serializable {

	private int groupId;
	private HarmfulSubstanceNationalStandardTable harmfulSubstanceNationalStandardTable;
	private TestDataProcessTable testDataProcessTable;
	private String substanceDetailedName;
	private Date testDataTime;
	private String testWorkshopJob;
	private String testResult;
	private BigDecimal mac;
	private BigDecimal ctwa;
	private BigDecimal cstel;
	private BigDecimal om;
	private Integer macScale;
	private Integer ctwaScale;
	private Integer cstelScale;
	private Integer omScale;
	private String resultType;
	private Set testDataProcessItems = new HashSet(0);

	public TestDataProcessGroup() {
	}

	public TestDataProcessGroup(int groupId) {
		this.groupId = groupId;
	}

	public TestDataProcessGroup(
			int groupId,
			HarmfulSubstanceNationalStandardTable harmfulSubstanceNationalStandardTable,
			TestDataProcessTable testDataProcessTable,
			String substanceDetailedName, Date testDataTime,
			String testWorkshopJob, String testResult, BigDecimal mac,
			BigDecimal ctwa, BigDecimal cstel, BigDecimal om, Integer macScale,
			Integer ctwaScale, Integer cstelScale, Integer omScale,
			String resultType, Set testDataProcessItems) {
		this.groupId = groupId;
		this.harmfulSubstanceNationalStandardTable = harmfulSubstanceNationalStandardTable;
		this.testDataProcessTable = testDataProcessTable;
		this.substanceDetailedName = substanceDetailedName;
		this.testDataTime = testDataTime;
		this.testWorkshopJob = testWorkshopJob;
		this.testResult = testResult;
		this.mac = mac;
		this.ctwa = ctwa;
		this.cstel = cstel;
		this.om = om;
		this.macScale = macScale;
		this.ctwaScale = ctwaScale;
		this.cstelScale = cstelScale;
		this.omScale = omScale;
		this.resultType = resultType;
		this.testDataProcessItems = testDataProcessItems;
	}

	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	public HarmfulSubstanceNationalStandardTable getHarmfulSubstanceNationalStandardTable() {
		return this.harmfulSubstanceNationalStandardTable;
	}

	public void setHarmfulSubstanceNationalStandardTable(
			HarmfulSubstanceNationalStandardTable harmfulSubstanceNationalStandardTable) {
		this.harmfulSubstanceNationalStandardTable = harmfulSubstanceNationalStandardTable;
	}

	public TestDataProcessTable getTestDataProcessTable() {
		return this.testDataProcessTable;
	}

	public void setTestDataProcessTable(
			TestDataProcessTable testDataProcessTable) {
		this.testDataProcessTable = testDataProcessTable;
	}

	public String getSubstanceDetailedName() {
		return this.substanceDetailedName;
	}

	public void setSubstanceDetailedName(String substanceDetailedName) {
		this.substanceDetailedName = substanceDetailedName;
	}

	public Date getTestDataTime() {
		return this.testDataTime;
	}

	public void setTestDataTime(Date testDataTime) {
		this.testDataTime = testDataTime;
	}

	public String getTestWorkshopJob() {
		return this.testWorkshopJob;
	}

	public void setTestWorkshopJob(String testWorkshopJob) {
		this.testWorkshopJob = testWorkshopJob;
	}

	public String getTestResult() {
		return this.testResult;
	}

	public void setTestResult(String testResult) {
		this.testResult = testResult;
	}

	public BigDecimal getMac() {
		return this.mac;
	}

	public void setMac(BigDecimal mac) {
		this.mac = mac;
	}

	public BigDecimal getCtwa() {
		return this.ctwa;
	}

	public void setCtwa(BigDecimal ctwa) {
		this.ctwa = ctwa;
	}

	public BigDecimal getCstel() {
		return this.cstel;
	}

	public void setCstel(BigDecimal cstel) {
		this.cstel = cstel;
	}

	public BigDecimal getOm() {
		return this.om;
	}

	public void setOm(BigDecimal om) {
		this.om = om;
	}

	public Integer getMacScale() {
		return this.macScale;
	}

	public void setMacScale(Integer macScale) {
		this.macScale = macScale;
	}

	public Integer getCtwaScale() {
		return this.ctwaScale;
	}

	public void setCtwaScale(Integer ctwaScale) {
		this.ctwaScale = ctwaScale;
	}

	public Integer getCstelScale() {
		return this.cstelScale;
	}

	public void setCstelScale(Integer cstelScale) {
		this.cstelScale = cstelScale;
	}

	public Integer getOmScale() {
		return this.omScale;
	}

	public void setOmScale(Integer omScale) {
		this.omScale = omScale;
	}

	public String getResultType() {
		return this.resultType;
	}

	public void setResultType(String resultType) {
		this.resultType = resultType;
	}

	public Set getTestDataProcessItems() {
		return this.testDataProcessItems;
	}

	public void setTestDataProcessItems(Set testDataProcessItems) {
		this.testDataProcessItems = testDataProcessItems;
	}

}
