package edu.tongji.anliantest.model;

// Generated 2014-9-30 13:52:24 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TestReportTable generated by hbm2java
 */
public class TestReportTable implements java.io.Serializable {

	private int tableId;
	private EmployeeInfo employeeInfoBySignerId;
	private ProjectInfo projectInfo;
	private EmployeeInfo employeeInfoByReviewerId;
	private EmployeeInfo employeeInfoByPreparerId;
	private String testReportNum;
	private String sampleName;
	private Integer sampleNum;
	private String sampleStatus;
	private String testProperty;
	private String testUnitName;
	private String testUnitAddress;
	private String entrustUnitName;
	private Date sampleTimeStart;
	private Date sampleTimeEnd;
	private Date receiveTimeStart;
	private Date receiveTimeEnd;
	private Date testTimeStart;
	private Date testTimeEnd;
	private Date reportTime;
	private Date tableTime;
	private Set testReportItems = new HashSet(0);

	public TestReportTable() {
	}

	public TestReportTable(int tableId) {
		this.tableId = tableId;
	}

	public TestReportTable(int tableId, EmployeeInfo employeeInfoBySignerId,
			ProjectInfo projectInfo, EmployeeInfo employeeInfoByReviewerId,
			EmployeeInfo employeeInfoByPreparerId, String testReportNum,
			String sampleName, Integer sampleNum, String sampleStatus,
			String testProperty, String testUnitName, String testUnitAddress,
			String entrustUnitName, Date sampleTimeStart, Date sampleTimeEnd,
			Date receiveTimeStart, Date receiveTimeEnd, Date testTimeStart,
			Date testTimeEnd, Date reportTime, Date tableTime,
			Set testReportItems) {
		this.tableId = tableId;
		this.employeeInfoBySignerId = employeeInfoBySignerId;
		this.projectInfo = projectInfo;
		this.employeeInfoByReviewerId = employeeInfoByReviewerId;
		this.employeeInfoByPreparerId = employeeInfoByPreparerId;
		this.testReportNum = testReportNum;
		this.sampleName = sampleName;
		this.sampleNum = sampleNum;
		this.sampleStatus = sampleStatus;
		this.testProperty = testProperty;
		this.testUnitName = testUnitName;
		this.testUnitAddress = testUnitAddress;
		this.entrustUnitName = entrustUnitName;
		this.sampleTimeStart = sampleTimeStart;
		this.sampleTimeEnd = sampleTimeEnd;
		this.receiveTimeStart = receiveTimeStart;
		this.receiveTimeEnd = receiveTimeEnd;
		this.testTimeStart = testTimeStart;
		this.testTimeEnd = testTimeEnd;
		this.reportTime = reportTime;
		this.tableTime = tableTime;
		this.testReportItems = testReportItems;
	}

	public int getTableId() {
		return this.tableId;
	}

	public void setTableId(int tableId) {
		this.tableId = tableId;
	}

	public EmployeeInfo getEmployeeInfoBySignerId() {
		return this.employeeInfoBySignerId;
	}

	public void setEmployeeInfoBySignerId(EmployeeInfo employeeInfoBySignerId) {
		this.employeeInfoBySignerId = employeeInfoBySignerId;
	}

	public ProjectInfo getProjectInfo() {
		return this.projectInfo;
	}

	public void setProjectInfo(ProjectInfo projectInfo) {
		this.projectInfo = projectInfo;
	}

	public EmployeeInfo getEmployeeInfoByReviewerId() {
		return this.employeeInfoByReviewerId;
	}

	public void setEmployeeInfoByReviewerId(
			EmployeeInfo employeeInfoByReviewerId) {
		this.employeeInfoByReviewerId = employeeInfoByReviewerId;
	}

	public EmployeeInfo getEmployeeInfoByPreparerId() {
		return this.employeeInfoByPreparerId;
	}

	public void setEmployeeInfoByPreparerId(
			EmployeeInfo employeeInfoByPreparerId) {
		this.employeeInfoByPreparerId = employeeInfoByPreparerId;
	}

	public String getTestReportNum() {
		return this.testReportNum;
	}

	public void setTestReportNum(String testReportNum) {
		this.testReportNum = testReportNum;
	}

	public String getSampleName() {
		return this.sampleName;
	}

	public void setSampleName(String sampleName) {
		this.sampleName = sampleName;
	}

	public Integer getSampleNum() {
		return this.sampleNum;
	}

	public void setSampleNum(Integer sampleNum) {
		this.sampleNum = sampleNum;
	}

	public String getSampleStatus() {
		return this.sampleStatus;
	}

	public void setSampleStatus(String sampleStatus) {
		this.sampleStatus = sampleStatus;
	}

	public String getTestProperty() {
		return this.testProperty;
	}

	public void setTestProperty(String testProperty) {
		this.testProperty = testProperty;
	}

	public String getTestUnitName() {
		return this.testUnitName;
	}

	public void setTestUnitName(String testUnitName) {
		this.testUnitName = testUnitName;
	}

	public String getTestUnitAddress() {
		return this.testUnitAddress;
	}

	public void setTestUnitAddress(String testUnitAddress) {
		this.testUnitAddress = testUnitAddress;
	}

	public String getEntrustUnitName() {
		return this.entrustUnitName;
	}

	public void setEntrustUnitName(String entrustUnitName) {
		this.entrustUnitName = entrustUnitName;
	}

	public Date getSampleTimeStart() {
		return this.sampleTimeStart;
	}

	public void setSampleTimeStart(Date sampleTimeStart) {
		this.sampleTimeStart = sampleTimeStart;
	}

	public Date getSampleTimeEnd() {
		return this.sampleTimeEnd;
	}

	public void setSampleTimeEnd(Date sampleTimeEnd) {
		this.sampleTimeEnd = sampleTimeEnd;
	}

	public Date getReceiveTimeStart() {
		return this.receiveTimeStart;
	}

	public void setReceiveTimeStart(Date receiveTimeStart) {
		this.receiveTimeStart = receiveTimeStart;
	}

	public Date getReceiveTimeEnd() {
		return this.receiveTimeEnd;
	}

	public void setReceiveTimeEnd(Date receiveTimeEnd) {
		this.receiveTimeEnd = receiveTimeEnd;
	}

	public Date getTestTimeStart() {
		return this.testTimeStart;
	}

	public void setTestTimeStart(Date testTimeStart) {
		this.testTimeStart = testTimeStart;
	}

	public Date getTestTimeEnd() {
		return this.testTimeEnd;
	}

	public void setTestTimeEnd(Date testTimeEnd) {
		this.testTimeEnd = testTimeEnd;
	}

	public Date getReportTime() {
		return this.reportTime;
	}

	public void setReportTime(Date reportTime) {
		this.reportTime = reportTime;
	}

	public Date getTableTime() {
		return this.tableTime;
	}

	public void setTableTime(Date tableTime) {
		this.tableTime = tableTime;
	}

	public Set getTestReportItems() {
		return this.testReportItems;
	}

	public void setTestReportItems(Set testReportItems) {
		this.testReportItems = testReportItems;
	}

}
