package edu.tongji.anliantest.model;

// Generated 2014-9-30 13:52:24 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TestReportItem generated by hbm2java
 */
public class TestReportItem implements java.io.Serializable {

	private int itemId;
	private TestReportTable testReportTable;
	private HarmfulSubstanceNationalStandardTable harmfulSubstanceNationalStandardTable;
	private String testWorkshopJob;
	private String substanceDetailedName;
	private Date testTime;
	private Integer testSampleId;
	private String testSampleNum;
	private BigDecimal testResult;
	private Integer testResultScale;
	private String testResultType;
	private BigDecimal testTouchTime;
	private Integer testTouchTimeScale;
	private Integer testCollectTime;

	public TestReportItem() {
	}

	public TestReportItem(int itemId) {
		this.itemId = itemId;
	}

	public TestReportItem(
			int itemId,
			TestReportTable testReportTable,
			HarmfulSubstanceNationalStandardTable harmfulSubstanceNationalStandardTable,
			String testWorkshopJob, String substanceDetailedName,
			Date testTime, Integer testSampleId, String testSampleNum,
			BigDecimal testResult, Integer testResultScale,
			String testResultType, BigDecimal testTouchTime,
			Integer testTouchTimeScale, Integer testCollectTime) {
		this.itemId = itemId;
		this.testReportTable = testReportTable;
		this.harmfulSubstanceNationalStandardTable = harmfulSubstanceNationalStandardTable;
		this.testWorkshopJob = testWorkshopJob;
		this.substanceDetailedName = substanceDetailedName;
		this.testTime = testTime;
		this.testSampleId = testSampleId;
		this.testSampleNum = testSampleNum;
		this.testResult = testResult;
		this.testResultScale = testResultScale;
		this.testResultType = testResultType;
		this.testTouchTime = testTouchTime;
		this.testTouchTimeScale = testTouchTimeScale;
		this.testCollectTime = testCollectTime;
	}

	public int getItemId() {
		return this.itemId;
	}

	public void setItemId(int itemId) {
		this.itemId = itemId;
	}

	public TestReportTable getTestReportTable() {
		return this.testReportTable;
	}

	public void setTestReportTable(TestReportTable testReportTable) {
		this.testReportTable = testReportTable;
	}

	public HarmfulSubstanceNationalStandardTable getHarmfulSubstanceNationalStandardTable() {
		return this.harmfulSubstanceNationalStandardTable;
	}

	public void setHarmfulSubstanceNationalStandardTable(
			HarmfulSubstanceNationalStandardTable harmfulSubstanceNationalStandardTable) {
		this.harmfulSubstanceNationalStandardTable = harmfulSubstanceNationalStandardTable;
	}

	public String getTestWorkshopJob() {
		return this.testWorkshopJob;
	}

	public void setTestWorkshopJob(String testWorkshopJob) {
		this.testWorkshopJob = testWorkshopJob;
	}

	public String getSubstanceDetailedName() {
		return this.substanceDetailedName;
	}

	public void setSubstanceDetailedName(String substanceDetailedName) {
		this.substanceDetailedName = substanceDetailedName;
	}

	public Date getTestTime() {
		return this.testTime;
	}

	public void setTestTime(Date testTime) {
		this.testTime = testTime;
	}

	public Integer getTestSampleId() {
		return this.testSampleId;
	}

	public void setTestSampleId(Integer testSampleId) {
		this.testSampleId = testSampleId;
	}

	public String getTestSampleNum() {
		return this.testSampleNum;
	}

	public void setTestSampleNum(String testSampleNum) {
		this.testSampleNum = testSampleNum;
	}

	public BigDecimal getTestResult() {
		return this.testResult;
	}

	public void setTestResult(BigDecimal testResult) {
		this.testResult = testResult;
	}

	public Integer getTestResultScale() {
		return this.testResultScale;
	}

	public void setTestResultScale(Integer testResultScale) {
		this.testResultScale = testResultScale;
	}

	public String getTestResultType() {
		return this.testResultType;
	}

	public void setTestResultType(String testResultType) {
		this.testResultType = testResultType;
	}

	public BigDecimal getTestTouchTime() {
		return this.testTouchTime;
	}

	public void setTestTouchTime(BigDecimal testTouchTime) {
		this.testTouchTime = testTouchTime;
	}

	public Integer getTestTouchTimeScale() {
		return this.testTouchTimeScale;
	}

	public void setTestTouchTimeScale(Integer testTouchTimeScale) {
		this.testTouchTimeScale = testTouchTimeScale;
	}

	public Integer getTestCollectTime() {
		return this.testCollectTime;
	}

	public void setTestCollectTime(Integer testCollectTime) {
		this.testCollectTime = testCollectTime;
	}

}
