package edu.tongji.anliantest.model;

// Generated 2014-9-30 13:52:24 by Hibernate Tools 3.4.0.CR1

/**
 * WorkTaskItem generated by hbm2java
 */
public class WorkTaskItem implements java.io.Serializable {

	private Integer itemId;
	private WorkTaskTable workTaskTable;
	private DepartmentInfo departmentInfo;
	private String workContent;
	private String workTimeLimit;

	public WorkTaskItem() {
	}

	public WorkTaskItem(WorkTaskTable workTaskTable,
			DepartmentInfo departmentInfo, String workContent,
			String workTimeLimit) {
		this.workTaskTable = workTaskTable;
		this.departmentInfo = departmentInfo;
		this.workContent = workContent;
		this.workTimeLimit = workTimeLimit;
	}

	public Integer getItemId() {
		return this.itemId;
	}

	public void setItemId(Integer itemId) {
		this.itemId = itemId;
	}

	public WorkTaskTable getWorkTaskTable() {
		return this.workTaskTable;
	}

	public void setWorkTaskTable(WorkTaskTable workTaskTable) {
		this.workTaskTable = workTaskTable;
	}

	public DepartmentInfo getDepartmentInfo() {
		return this.departmentInfo;
	}

	public void setDepartmentInfo(DepartmentInfo departmentInfo) {
		this.departmentInfo = departmentInfo;
	}

	public String getWorkContent() {
		return this.workContent;
	}

	public void setWorkContent(String workContent) {
		this.workContent = workContent;
	}

	public String getWorkTimeLimit() {
		return this.workTimeLimit;
	}

	public void setWorkTimeLimit(String workTimeLimit) {
		this.workTimeLimit = workTimeLimit;
	}

}
