package edu.tongji.anliantest.model;

// Generated 2014-9-30 13:52:24 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * WorkTaskTable generated by hbm2java
 */
public class WorkTaskTable implements java.io.Serializable {

	private Integer tableId;
	private ProjectInfo projectInfo;
	private EmployeeInfo employeeInfo;
	private String tableNum;
	private String tableType;
	private Date taskTime;
	private Set workTaskItems = new HashSet(0);

	public WorkTaskTable() {
	}

	public WorkTaskTable(ProjectInfo projectInfo, EmployeeInfo employeeInfo,
			String tableNum, String tableType, Date taskTime, Set workTaskItems) {
		this.projectInfo = projectInfo;
		this.employeeInfo = employeeInfo;
		this.tableNum = tableNum;
		this.tableType = tableType;
		this.taskTime = taskTime;
		this.workTaskItems = workTaskItems;
	}

	public Integer getTableId() {
		return this.tableId;
	}

	public void setTableId(Integer tableId) {
		this.tableId = tableId;
	}

	public ProjectInfo getProjectInfo() {
		return this.projectInfo;
	}

	public void setProjectInfo(ProjectInfo projectInfo) {
		this.projectInfo = projectInfo;
	}

	public EmployeeInfo getEmployeeInfo() {
		return this.employeeInfo;
	}

	public void setEmployeeInfo(EmployeeInfo employeeInfo) {
		this.employeeInfo = employeeInfo;
	}

	public String getTableNum() {
		return this.tableNum;
	}

	public void setTableNum(String tableNum) {
		this.tableNum = tableNum;
	}

	public String getTableType() {
		return this.tableType;
	}

	public void setTableType(String tableType) {
		this.tableType = tableType;
	}

	public Date getTaskTime() {
		return this.taskTime;
	}

	public void setTaskTime(Date taskTime) {
		this.taskTime = taskTime;
	}

	public Set getWorkTaskItems() {
		return this.workTaskItems;
	}

	public void setWorkTaskItems(Set workTaskItems) {
		this.workTaskItems = workTaskItems;
	}

}
