package edu.tongji.anliantest.model;

// Generated 2014-5-5 12:47:38 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WorkTaskTable generated by hbm2java
 */
@Entity
@Table(name = "work_task_table", catalog = "anliantest")
public class WorkTaskTable implements java.io.Serializable {

	private Integer tableId;
	private EmployeeInfo employeeInfo;
	private String tableNum;
	private String tableType;
	private Date taskTime;
	private Integer projectId;
	private Set<WorkTaskItem> workTaskItems = new HashSet<WorkTaskItem>(0);

	public WorkTaskTable() {
	}

	public WorkTaskTable(EmployeeInfo employeeInfo, String tableNum,
			String tableType, Date taskTime, Integer projectId,
			Set<WorkTaskItem> workTaskItems) {
		this.employeeInfo = employeeInfo;
		this.tableNum = tableNum;
		this.tableType = tableType;
		this.taskTime = taskTime;
		this.projectId = projectId;
		this.workTaskItems = workTaskItems;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "table_id", unique = true, nullable = false)
	public Integer getTableId() {
		return this.tableId;
	}

	public void setTableId(Integer tableId) {
		this.tableId = tableId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "task_employee_id")
	public EmployeeInfo getEmployeeInfo() {
		return this.employeeInfo;
	}

	public void setEmployeeInfo(EmployeeInfo employeeInfo) {
		this.employeeInfo = employeeInfo;
	}

	@Column(name = "table_num", length = 13)
	public String getTableNum() {
		return this.tableNum;
	}

	public void setTableNum(String tableNum) {
		this.tableNum = tableNum;
	}

	@Column(name = "table_type", length = 3)
	public String getTableType() {
		return this.tableType;
	}

	public void setTableType(String tableType) {
		this.tableType = tableType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "task_time", length = 0)
	public Date getTaskTime() {
		return this.taskTime;
	}

	public void setTaskTime(Date taskTime) {
		this.taskTime = taskTime;
	}

	@Column(name = "project_id")
	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "workTaskTable")
	public Set<WorkTaskItem> getWorkTaskItems() {
		return this.workTaskItems;
	}

	public void setWorkTaskItems(Set<WorkTaskItem> workTaskItems) {
		this.workTaskItems = workTaskItems;
	}

}
